language: elixir
sudo: false
elixir:
- 1.7.4
- 1.8.2
otp_release:
- 21.3
- 22.0
after_script:
- MIX_ENV=docs mix deps.get
- MIX_ENV=docs mix inch.report
deploy:
  provider: script
  script: scripts/hex.sh
  on:
    tags: true
    repo: jeffutter/particle-elixir
env:
  global:
  - secure: cPefm6Bf3MLsPyovwme20kIqc2ybfYvwJNFzdR1k1AZsjt/a9DjnsgO3uMpaVGQ+rwj+MrZ6ioPu15ENWjFyaBJlNI3jMvemIGOBKCoEwJPAsnFl10AdXSYx0EQhv8boFTv+NO/d1Ge0TQkvYTHUS32EaCgyx+WLfkoJXmW6ixH0yw0kISJ5UgSK5myjvhaEXLE2wSg6pTpctHKrg+pA1EuCvEsDJN5YJx09JGQscRgIE7Ivn7xa/oDcYOF7lcX/5Xn8Fz75V1bfoU2gZVVbc5NwRkXcmlweUAHfXY1v5Ih+6Yon8VT1VO+K2NAktLRnZLuFrUjXVlk6sc4ogaAcmCdbttYLkAFxyuii7x2SlWF5Pezz2xe3ZdgTmoDdrbTzx4rk6DODnEbe82MPVON9IckljoXID2GowCwHs6uecEABAY1UKGHU+QzpfuaEelLtdvD9FaTuCIm0QV45L2lnfzQOuQW2kGVOwwno8DNkaa0BTIqJPiCM/lO0U837caiM5z36dGMN8mEqYj4lDRWceIikC2AAiwkRryfur+yBCIZDBE0MjNvqJ7x67kmhT26Xv+2lWc31nvQnT5t1vusvgZkd6pw565HJJA8Hv5eY0Nekop9vzVVp+ngdtfu/fgiejNQ9ieGPAsqAG9AM5CVobzrrnh73BwdRC3q+4Rt7I74=
